services:
  web:
    container_name: chat-universal-client
    image: ghcr.io/gipierogiglio-prog/chat-universal-client:latest
    ports:
      - "3002:80"
    networks:
      - devgiglio-network
    restart: unless-stopped

networks:
  devgiglio-network:
    external: true
